### ISSUE TITLE
Cannot compile last version on Ubuntu 24.04

### ISSUE THREAD

**Issue by hugo-akaora** [AllanChain/sane-break#24]
Hello,

I tried to compile sane-break on Ubuntu 24.04 (Actually Linux Mint 22.1 which is based on the above).

I installed:
```
apt install qt6-base-dev qt6-multimedia-dev
apt install libxss-dev # X support
apt install qt6-wayland-dev liblayershellqtinterface-dev # Wayland support
apt install cmake
```

I ran: 
```
git clone https://github.com/AllanChain/sane-break
cd sane-break
mkdir build
cd build
cmake ..
cmake --build . --parallel
sudo cmake --install .
```

Output:
```
[ 79%] Building CXX object CMakeFiles/sane-break.dir/qwayland-ext-idle-notify-v1.cpp.o
/home/hugo/Téléchargements/sane-break/src/linux/wayland/idle.cpp: In constructor ‘IdleTimeWayland::IdleTimeWayland()’:
/home/hugo/Téléchargements/sane-break/src/linux/wayland/idle.cpp:16:21: error: ‘QWaylandApplication’ is not a member of ‘QNativeInterface’; did you mean ‘QX11Application’?
   16 |   QNativeInterface::QWaylandApplication *waylandApp =
      |                     ^~~~~~~~~~~~~~~~~~~
      |                     QX11Application
/home/hugo/Téléchargements/sane-break/src/linux/wayland/idle.cpp:16:42: error: ‘waylandApp’ was not declared in this scope
   16 |   QNativeInterface::QWaylandApplication *waylandApp =
      |                                          ^~~~~~~~~~
/home/hugo/Téléchargements/sane-break/src/linux/wayland/idle.cpp:17:50: error: ‘QWaylandApplication’ is not a member of ‘QNativeInterface’; did you mean ‘QX11Application’?
   17 |       qGuiApp->nativeInterface<QNativeInterface::QWaylandApplication>();
      |                                                  ^~~~~~~~~~~~~~~~~~~
      |                                                  QX11Application
/home/hugo/Téléchargements/sane-break/src/linux/wayland/idle.cpp:17:70: error: no matching function for call to ‘QGuiApplication::nativeInterface<<expression error> >()’
   17 |       qGuiApp->nativeInterface<QNativeInterface::QWaylandApplication>();
      |                                                                      ^
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qcoreapplication.h:16,
                 from /usr/include/x86_64-linux-gnu/qt6/QtGui/qguiapplication.h:8,
                 from /usr/include/x86_64-linux-gnu/qt6/QtGui/QGuiApplication:1,
                 from /home/hugo/Téléchargements/sane-break/src/linux/wayland/idle.cpp:10:
/usr/include/x86_64-linux-gnu/qt6/QtGui/qguiapplication.h:140:5: note: candidate: ‘template<class NativeInterface, class TypeInfo, class BaseType, typename std::enable_if<TypeInfo::isCompatibleWith<QGuiApplication>, bool>::type <anonymous> > NativeInterface* QGuiApplication::nativeInterface() const’
  140 |     QT_DECLARE_NATIVE_INTERFACE_ACCESSOR(QGuiApplication)
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/x86_64-linux-gnu/qt6/QtGui/qguiapplication.h:140:5: note:   template argument deduction/substitution failed:
/home/hugo/Téléchargements/sane-break/src/linux/wayland/idle.cpp:17:70: error: template argument 1 is invalid
   17 |       qGuiApp->nativeInterface<QNativeInterface::QWaylandApplication>();
      |                                                                      ^
gmake[2]: *** [CMakeFiles/sane-break.dir/build.make:298 : CMakeFiles/sane-break.dir/src/linux/wayland/idle.cpp.o] Erreur 1
gmake[2]: *** Attente des tâches non terminées....
/home/hugo/Téléchargements/sane-break/src/window-manager.cpp: In member function ‘void BreakWindowManager::createWindows()’:
/home/hugo/Téléchargements/sane-break/src/window-manager.cpp:67:17: error: ‘class LayerShellQt::Window’ has no member named ‘setCloseOnDismissed’
   67 |         window->setCloseOnDismissed(true);
      |                 ^~~~~~~~~~~~~~~~~~~
gmake[2]: *** [CMakeFiles/sane-break.dir/build.make:256 : CMakeFiles/sane-break.dir/src/window-manager.cpp.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:103 : CMakeFiles/sane-break.dir/all] Erreur 2
gmake: *** [Makefile:136 : all] Erreur 2
-- Install configuration: ""
CMake Error at cmake_install.cmake:52 (file):
  file INSTALL cannot find
  "/home/hugo/Téléchargements/sane-break/build/sane-break": No such file or
  directory.
```

I must say that I'm running Cinnamon desktop running x11

Thank you, looking forward to test sane-break!
Hug

**Comment by AllanChain** [comment]
Looks like there's some problem compiling with Wayland support. Actually, you don't need to `apt install qt6-wayland-dev liblayershellqtinterface-dev` if you are using X11. The Wayland support will be automatically disabled and not compiled after `apt remove qt6-wayland-dev liblayershellqtinterface-dev`.

**Comment by hugo-akaora** [comment]
Hello, thank you @AllanChain 

I removed Wayland dependencies and now I have:
```
/tmp/sane-break/src/idle-time.cpp: In static member function ‘static SystemIdleTime* SystemIdleTime::createIdleTimer()’:
/tmp/sane-break/src/idle-time.cpp:34:11: error: no matching function for call to ‘QMessageLogger::fatal()’
   34 |     qFatal() << "Please compile with Wayland support.";
      |           ^
In file included from /usr/include/x86_64-linux-gnu/qt6/QtCore/qglobal.h:1399,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/qnamespace.h:8,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/qobjectdefs.h:12,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/qobject.h:10,
                 from /usr/include/x86_64-linux-gnu/qt6/QtCore/QObject:1,
                 from /tmp/sane-break/src/idle-time.h:8,
                 from /tmp/sane-break/src/idle-time.cpp:5:
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlogging.h:94:10: note: candidate: ‘void QMessageLogger::fatal(const char*, ...) const’
   94 |     void fatal(const char *msg, ...) const noexcept Q_ATTRIBUTE_FORMAT_PRINTF(2, 3);
      |          ^~~~~
/usr/include/x86_64-linux-gnu/qt6/QtCore/qlogging.h:94:10: note:   candidate expects 1 argument, 0 provided
gmake[2]: *** [CMakeFiles/sane-break.dir/build.make:154 : CMakeFiles/sane-break.dir/src/idle-time.cpp.o] Erreur 1
gmake[2]: *** Attente des tâches non terminées....
gmake[1]: *** [CMakeFiles/Makefile2:103 : CMakeFiles/sane-break.dir/all] Erreur 2
gmake: *** [Makefile:136 : all] Erreur 2
[sudo] Mot de passe de hugo :         
-- Install configuration: ""
CMake Error at cmake_install.cmake:52 (file):
  file INSTALL cannot find "/tmp/sane-break/build/sane-break": No such file
  or directory.
```

Is there something I can do, maybe a flag, to not compile wayland?

**Comment by AllanChain** [comment]
Are you sure you are running on X11? What's the output of the following command?
```sh
echo $XDG_SESSION_TYPE
```

**Comment by AllanChain** [comment]
Sorry, I misread the error message. The Wayland support is indeed disabled, and the problem seems related to Qt version. Can you provide your Qt version?

**Comment by AllanChain** [comment]
The latest commit (a16dc6d) may fix your problem.

**Comment by hugo-akaora** [comment]
Hi, I had to reinstall wayland dependencies to be able to proceed then I have another error:
```
/home/hugo/sane-break/src/idle-time.cpp:11:10: fatal error: QtLogging: Aucun fichier ou dossier de ce nom
   11 | #include <QtLogging>
      |          ^~~~~~~~~~~
compilation terminated.
```
Guess my qt version is too old? 
Using Qt version 5.15.13

**Comment by AllanChain** [comment]
You can manually replace `QtLogging` with `QtGlobal` in `/home/hugo/sane-break/src/idle-time.cpp` and try again. In the meantime, I will try to reproduce and debug this on a lower version of Qt.

**Comment by AllanChain** [comment]
I can compile on Qt 6.4.2 with the latest commit 696394e

**Comment by hugo-akaora** [comment]
Oh, it's working!
You made my day, thank you! <3
